### ISSUE TITLE
关于这种控件的实现

### ISSUE THREAD

**Issue by msdx** [boluoge/TextCheckBox#1]
其实想问的是，用这个控件，与直接用一个selector，并且把checkbox的button属性设为@null，有何不同呢？

**Comment by boluoge** [comment]
其实我写的是一个滑动的WeekPicker,TextCheckBox只是用来显示一周的某一天。后来因为我想给checkbox做动画，所以才独立出来了,互不影响。用selector也可以啊，不过我以前用过，效果不好。padding这些都不好控制，所以自己重写了一个。
